language: go

go:
  - 1.x

# Derived from https://github.com/lib/pq/blob/master/.travis.yml
before_install:
  - ./travis/before_install.bash

env:
  global:
    - GO111MODULE=on

  matrix:
    - PGVERSION=11
    - PGVERSION=10

before_script:
  - ./travis/before_script.bash

script:
  - ./travis/script.bash
