// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iidy.proto

/*
Package iidy is a generated protocol buffer package.

It is generated from these files:
	iidy.proto

It has these top-level messages:
	Entry
	Entries
*/
package iidy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	List string `protobuf:"bytes,1,opt,name=list" json:"list,omitempty"`
	Item string `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetList() string {
	if m != nil {
		return m.List
	}
	return ""
}

func (m *Entry) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

type Entries struct {
	List  string   `protobuf:"bytes,1,opt,name=list" json:"list,omitempty"`
	Items []string `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *Entries) Reset()                    { *m = Entries{} }
func (m *Entries) String() string            { return proto.CompactTextString(m) }
func (*Entries) ProtoMessage()               {}
func (*Entries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Entries) GetList() string {
	if m != nil {
		return m.List
	}
	return ""
}

func (m *Entries) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "iidy.Entry")
	proto.RegisterType((*Entries)(nil), "iidy.Entries")
}

func init() { proto.RegisterFile("iidy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcc, 0x4c, 0xa9,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xf4, 0xb9, 0x58, 0x5d, 0xf3,
	0x4a, 0x8a, 0x2a, 0x85, 0x84, 0xb8, 0x58, 0x72, 0x32, 0x8b, 0x4b, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0xc0, 0x6c, 0x90, 0x58, 0x66, 0x49, 0x6a, 0xae, 0x04, 0x13, 0x44, 0x0c, 0xc4, 0x56,
	0x32, 0xe6, 0x62, 0x07, 0x69, 0xc8, 0x4c, 0x2d, 0xc6, 0xaa, 0x45, 0x84, 0x8b, 0x15, 0xa4, 0xac,
	0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0x33, 0x08, 0xc2, 0x49, 0x62, 0x03, 0x5b, 0x69, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x86, 0xaa, 0x0d, 0x0b, 0x80, 0x00, 0x00, 0x00,
}
