// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iidy.proto

/*
Package iidy is a generated protocol buffer package.

It is generated from these files:
	iidy.proto

It has these top-level messages:
	Entry
	Entries
	Reply
	GetReply
*/
package iidy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A single list entry
type Entry struct {
	List string `protobuf:"bytes,1,opt,name=list" json:"list,omitempty"`
	Item string `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetList() string {
	if m != nil {
		return m.List
	}
	return ""
}

func (m *Entry) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

// A batch of list entries
type Entries struct {
	List  string   `protobuf:"bytes,1,opt,name=list" json:"list,omitempty"`
	Items []string `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *Entries) Reset()                    { *m = Entries{} }
func (m *Entries) String() string            { return proto.CompactTextString(m) }
func (*Entries) ProtoMessage()               {}
func (*Entries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Entries) GetList() string {
	if m != nil {
		return m.List
	}
	return ""
}

func (m *Entries) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

// A reply from the service, saying what was done,
// and how many times.
type Reply struct {
	Verb  string `protobuf:"bytes,1,opt,name=verb" json:"verb,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Reply) GetVerb() string {
	if m != nil {
		return m.Verb
	}
	return ""
}

func (m *Reply) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// A reply from a Get, showing the number of attempts
// for this item. When the number of attempts is 0,
// check the OK field to determine if the attempts is
// 0 because the item was found and not attempted,
// or if it's because the item was not present.
type GetReply struct {
	Attempts int64 `protobuf:"varint,1,opt,name=attempts" json:"attempts,omitempty"`
	Ok       bool  `protobuf:"varint,2,opt,name=ok" json:"ok,omitempty"`
}

func (m *GetReply) Reset()                    { *m = GetReply{} }
func (m *GetReply) String() string            { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()               {}
func (*GetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetReply) GetAttempts() int64 {
	if m != nil {
		return m.Attempts
	}
	return 0
}

func (m *GetReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Entry)(nil), "iidy.Entry")
	proto.RegisterType((*Entries)(nil), "iidy.Entries")
	proto.RegisterType((*Reply)(nil), "iidy.Reply")
	proto.RegisterType((*GetReply)(nil), "iidy.GetReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RPCer service

type RPCerClient interface {
	// Puts a new value in a list
	Put(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Reply, error)
	// Gets a value's number of attempts from a list
	Get(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*GetReply, error)
}

type rPCerClient struct {
	cc *grpc.ClientConn
}

func NewRPCerClient(cc *grpc.ClientConn) RPCerClient {
	return &rPCerClient{cc}
}

func (c *rPCerClient) Put(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/iidy.RPCer/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCerClient) Get(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := grpc.Invoke(ctx, "/iidy.RPCer/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RPCer service

type RPCerServer interface {
	// Puts a new value in a list
	Put(context.Context, *Entry) (*Reply, error)
	// Gets a value's number of attempts from a list
	Get(context.Context, *Entry) (*GetReply, error)
}

func RegisterRPCerServer(s *grpc.Server, srv RPCerServer) {
	s.RegisterService(&_RPCer_serviceDesc, srv)
}

func _RPCer_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCerServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iidy.RPCer/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCerServer).Put(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCer_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iidy.RPCer/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCerServer).Get(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iidy.RPCer",
	HandlerType: (*RPCerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _RPCer_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RPCer_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iidy.proto",
}

func init() { proto.RegisterFile("iidy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x77, 0x93, 0x8d, 0x76, 0x47, 0xd8, 0x43, 0xf0, 0x50, 0xf6, 0xb4, 0x06, 0x0f, 0x7b,
	0x5a, 0xd1, 0x82, 0x2f, 0x20, 0xd2, 0x6b, 0xc9, 0x1b, 0x58, 0x9d, 0x43, 0xe8, 0x9f, 0x94, 0x64,
	0x2a, 0xf4, 0xed, 0x25, 0x13, 0xeb, 0x41, 0xf6, 0xf6, 0xfd, 0x86, 0xf9, 0xe5, 0x63, 0x02, 0xe0,
	0xdc, 0xd7, 0x72, 0x99, 0x82, 0x27, 0xaf, 0x77, 0x29, 0x9b, 0x27, 0x50, 0xef, 0x23, 0x85, 0x45,
	0x6b, 0xd8, 0xf5, 0x2e, 0x52, 0xb9, 0x3d, 0x6d, 0xcf, 0x7b, 0xcb, 0x39, 0xcd, 0x1c, 0xe1, 0x50,
	0x8a, 0x3c, 0x4b, 0xd9, 0x54, 0x70, 0x9b, 0x04, 0x87, 0xf1, 0xaa, 0x72, 0x0f, 0x2a, 0xad, 0xc5,
	0x52, 0x9c, 0xe4, 0x79, 0x6f, 0x33, 0x98, 0x67, 0x50, 0x16, 0xa7, 0x9e, 0x5b, 0xbe, 0x31, 0xb4,
	0xab, 0x92, 0x72, 0x52, 0x3e, 0xfd, 0x3c, 0x12, 0xd7, 0x48, 0x9b, 0xc1, 0xbc, 0x42, 0x51, 0x23,
	0x65, 0xeb, 0x08, 0xc5, 0x07, 0x11, 0x0e, 0x13, 0x45, 0x36, 0xa5, 0xfd, 0x63, 0x7d, 0x00, 0xe1,
	0x3b, 0x56, 0x0b, 0x2b, 0x7c, 0xf7, 0xd2, 0x80, 0xb2, 0xcd, 0x1b, 0x06, 0xfd, 0x00, 0xb2, 0x99,
	0x49, 0xdf, 0x5d, 0xf8, 0x66, 0x3e, 0xf2, 0xf8, 0x0b, 0xfc, 0xaa, 0xd9, 0xe8, 0x47, 0x90, 0x35,
	0xfe, 0x5b, 0x39, 0x64, 0x58, 0xbb, 0xcd, 0xa6, 0xbd, 0xe1, 0xff, 0xaa, 0x7e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x9d, 0x20, 0x58, 0x4f, 0x3d, 0x01, 0x00, 0x00,
}
